### ISSUE TITLE
Merchant Items Show Page

### ISSUE THREAD

**Issue by rebeckahendricks** [Dominicod/little-esty-shop#9]
Merchant Items Show Page

As a merchant,
When I click on the name of an item from the merchant items index page,
Then I am taken to that merchant's item's show page (/merchants/merchant_id/items/item_id)
And I see all of the item's attributes including:

- Name
- Description
- Current Selling Price

**Comment by thayes87** [comment]
This story requires links for the items on the merchant items index page but story #8 does not require links. Need to resolve. Tests are written for Show page as if links are in the index page.
